- name: Setting up catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable current nodejs version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable nodejs version 18
    ansible.builtin.command: dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  # - name: Add roboshop user
  #   ansible.builtin.user:
  #   name: roboshop

  # - name: Create directory app
  #   ansible.builtin.file:
  #     path: /app
  #     state: directory
  
  # - name:

